version: '3.5'

services: 
  nginx-proxy:
    image: nginx:alpine
    restart: always
    volumes:
      - ./conf.d:/etc/nginx/conf.d/
      - ./nginx-log:/var/log/nginx
      - ./web:/usr/share/nginx
    ports:
      - 80:80
networks: 
  default: 
    external: 
      name: project-final